// <auto-generated />
using System;
using LabAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabAPI.Migrations
{
    [DbContext(typeof(MedicalLabsContext))]
    [Migration("20260411183510_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabAPI.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ExpiryDays")
                        .HasColumnType("tinyint")
                        .HasColumnName("expiry_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sample_type");

                    b.HasKey("Id")
                        .HasName("analysis_pkey");

                    b.HasIndex(new[] { "Name" }, "analysis_name_unique")
                        .IsUnique();

                    b.ToTable("analysis", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("office_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<TimeOnly>("VisitTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("visit_time");

                    b.HasKey("Id")
                        .HasName("appointment_pkey");

                    b.HasIndex("PatientId");

                    b.HasIndex(new[] { "OfficeId", "VisitDate" }, "idx_appointment_office_date")
                        .IsDescending(false, true);

                    b.ToTable("appointment", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("employee_pkey");

                    b.HasIndex(new[] { "Email" }, "employee_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "employee_phone_unique")
                        .IsUnique();

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("day_of_week");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("end_time");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("office_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("est_pkey");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.ToTable("employee_schedule", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.EmployeeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly?>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("end_time");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("office_id");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shift_date");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("work")
                        .HasColumnName("shift_type");

                    b.Property<TimeOnly?>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("es_pkey");

                    b.HasIndex("OfficeId");

                    b.HasIndex(new[] { "EmployeeId", "ShiftDate" }, "es_employee_date_unique")
                        .IsUnique();

                    b.ToTable("employee_shift", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.LabOrder", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("unpaid")
                        .HasColumnName("status");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("total_price");

                    b.HasKey("Number")
                        .HasName("lab_order_pkey");

                    b.HasIndex("PatientId");

                    b.ToTable("lab_order", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("office_pkey");

                    b.HasIndex(new[] { "Number", "City" }, "office_number_city_unique")
                        .IsUnique();

                    b.ToTable("office", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.OfficeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("close_time");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("day_of_week");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("office_id");

                    b.Property<TimeOnly>("OpenTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("open_time");

                    b.HasKey("Id")
                        .HasName("office_schedule_pkey");

                    b.HasIndex(new[] { "OfficeId", "DayOfWeek" }, "office_schedule_unique")
                        .IsUnique();

                    b.ToTable("office_schedule", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.OrderAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int")
                        .HasColumnName("analysis_id");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("order_number");

                    b.HasKey("Id")
                        .HasName("order_analysis_pkey");

                    b.HasIndex("AnalysisId");

                    b.HasIndex(new[] { "OrderNumber", "AnalysisId" }, "order_analysis_unique")
                        .IsUnique();

                    b.ToTable("order_analysis", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int")
                        .HasColumnName("analysis_id");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("parameter_name");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("parameter_pkey");

                    b.HasIndex("AnalysisId");

                    b.HasIndex(new[] { "ParameterName", "AnalysisId" }, "parameter_name_analysis_unique")
                        .IsUnique();

                    b.ToTable("parameter", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.ParameterNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("AgeMax")
                        .HasColumnType("tinyint")
                        .HasColumnName("age_max");

                    b.Property<byte>("AgeMin")
                        .HasColumnType("tinyint")
                        .HasColumnName("age_min");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("min_value");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.HasKey("Id")
                        .HasName("parameter_norm_pkey");

                    b.HasIndex(new[] { "ParameterId", "AgeMin", "AgeMax", "Gender" }, "parameter_norm_unique")
                        .IsUnique();

                    b.ToTable("parameter_norm", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.ParameterResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsNormal")
                        .HasColumnType("bit")
                        .HasColumnName("is_normal");

                    b.Property<decimal?>("MeasuredValue")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("measured_value");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.Property<int>("ResultId")
                        .HasColumnType("int")
                        .HasColumnName("result_id");

                    b.HasKey("Id")
                        .HasName("parameter_result_pkey");

                    b.HasIndex("ParameterId");

                    b.HasIndex(new[] { "ResultId", "ParameterId" }, "parameter_result_result_parameter_unique")
                        .IsUnique();

                    b.ToTable("parameter_result", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("patient_pkey");

                    b.HasIndex(new[] { "LastName", "FirstName", "MiddleName" }, "idx_patient_name_search");

                    b.HasIndex(new[] { "Phone" }, "patient_phone_unique")
                        .IsUnique();

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conclusion");

                    b.Property<DateTime?>("ResultDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("result_date");

                    b.Property<int>("SampleId")
                        .HasColumnType("int")
                        .HasColumnName("sample_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("result_pkey");

                    b.HasIndex("AnalysisId");

                    b.HasIndex(new[] { "SampleId" }, "idx_result_sample_lookup");

                    b.HasIndex(new[] { "SampleId", "AnalysisId" }, "result_sample_analysis_unique")
                        .IsUnique();

                    b.ToTable("result", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CollectionDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("collection_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("waiting")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("sample_pkey");

                    b.HasIndex(new[] { "OrderNumber" }, "idx_sample_order_search");

                    b.ToTable("sample", null, t =>
                        {
                            t.HasTrigger("sample_set_expiry_date");

                            t.HasTrigger("sample_status_sync_order");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LabAPI.Models.AppUser", b =>
                {
                    b.HasOne("LabAPI.Models.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("LabAPI.Models.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LabAPI.Models.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("LabAPI.Models.AppUser", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabAPI.Models.Appointment", b =>
                {
                    b.HasOne("LabAPI.Models.Office", "Office")
                        .WithMany("Appointments")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("appointment_office_fkey");

                    b.HasOne("LabAPI.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("appointment_patient_fkey");

                    b.Navigation("Office");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabAPI.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("LabAPI.Models.Employee", "Employee")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("est_employee_fkey");

                    b.HasOne("LabAPI.Models.Office", "Office")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("est_office_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("LabAPI.Models.EmployeeShift", b =>
                {
                    b.HasOne("LabAPI.Models.Employee", "Employee")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("es_employee_fkey");

                    b.HasOne("LabAPI.Models.Office", "Office")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("es_office_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("LabAPI.Models.LabOrder", b =>
                {
                    b.HasOne("LabAPI.Models.Patient", "Patient")
                        .WithMany("LabOrders")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("lab_order_patient_fkey");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabAPI.Models.OfficeSchedule", b =>
                {
                    b.HasOne("LabAPI.Models.Office", "Office")
                        .WithMany("OfficeSchedules")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("office_schedule_office_fkey");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("LabAPI.Models.OrderAnalysis", b =>
                {
                    b.HasOne("LabAPI.Models.Analysis", "Analysis")
                        .WithMany("OrderAnalyses")
                        .HasForeignKey("AnalysisId")
                        .IsRequired()
                        .HasConstraintName("order_analysis_analysis_fkey");

                    b.HasOne("LabAPI.Models.LabOrder", "OrderNumberNavigation")
                        .WithMany("OrderAnalyses")
                        .HasForeignKey("OrderNumber")
                        .IsRequired()
                        .HasConstraintName("order_analysis_order_fkey");

                    b.Navigation("Analysis");

                    b.Navigation("OrderNumberNavigation");
                });

            modelBuilder.Entity("LabAPI.Models.Parameter", b =>
                {
                    b.HasOne("LabAPI.Models.Analysis", "Analysis")
                        .WithMany("Parameters")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("parameter_analysis_fkey");

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("LabAPI.Models.ParameterNorm", b =>
                {
                    b.HasOne("LabAPI.Models.Parameter", "Parameter")
                        .WithMany("ParameterNorms")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("parameter_norm_fkey");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("LabAPI.Models.ParameterResult", b =>
                {
                    b.HasOne("LabAPI.Models.Parameter", "Parameter")
                        .WithMany("ParameterResults")
                        .HasForeignKey("ParameterId")
                        .IsRequired()
                        .HasConstraintName("parameter_result_parameter_fkey");

                    b.HasOne("LabAPI.Models.Result", "Result")
                        .WithMany("ParameterResults")
                        .HasForeignKey("ResultId")
                        .IsRequired()
                        .HasConstraintName("parameter_result_result_fkey");

                    b.Navigation("Parameter");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("LabAPI.Models.Result", b =>
                {
                    b.HasOne("LabAPI.Models.Analysis", "Analysis")
                        .WithMany("Results")
                        .HasForeignKey("AnalysisId")
                        .IsRequired()
                        .HasConstraintName("result_analysis_fkey");

                    b.HasOne("LabAPI.Models.Sample", "Sample")
                        .WithMany("Results")
                        .HasForeignKey("SampleId")
                        .IsRequired()
                        .HasConstraintName("result_sample_fkey");

                    b.Navigation("Analysis");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("LabAPI.Models.Sample", b =>
                {
                    b.HasOne("LabAPI.Models.LabOrder", "OrderNumberNavigation")
                        .WithMany("Samples")
                        .HasForeignKey("OrderNumber")
                        .IsRequired()
                        .HasConstraintName("sample_order_fkey");

                    b.Navigation("OrderNumberNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LabAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LabAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LabAPI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LabAPI.Models.Analysis", b =>
                {
                    b.Navigation("OrderAnalyses");

                    b.Navigation("Parameters");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("LabAPI.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSchedules");

                    b.Navigation("EmployeeShifts");
                });

            modelBuilder.Entity("LabAPI.Models.LabOrder", b =>
                {
                    b.Navigation("OrderAnalyses");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("LabAPI.Models.Office", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EmployeeSchedules");

                    b.Navigation("EmployeeShifts");

                    b.Navigation("OfficeSchedules");
                });

            modelBuilder.Entity("LabAPI.Models.Parameter", b =>
                {
                    b.Navigation("ParameterNorms");

                    b.Navigation("ParameterResults");
                });

            modelBuilder.Entity("LabAPI.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("LabAPI.Models.Result", b =>
                {
                    b.Navigation("ParameterResults");
                });

            modelBuilder.Entity("LabAPI.Models.Sample", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
